baseURL = "https://hugo-386.vercel.app/"
title = "HUGO.386"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "HUGO.386"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Welcome to the early 90s!" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "Hello, @Samael3003 here. I always had a little nostalgia towards old and retro themes and games. This is nothing but a simple way of reliving the Past we GEN-Z always missed..."

    # The name to display in the copyright section in the footer
    copyrightname = "@Samael3003"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = "https://hugo-386.vercel.app/"

    # Show the "built on Hugo" disclaimer
    showhugo = true

    # Urls for social networks
    facebook = "https://facebook.com"
    twitter = "https://twitter.com"
    linkedin = "https://linkedin.com"
    github = "https://github.com"
    gitlab = "https://gitlab.com"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "@Samael3003"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = "https://hugo-386.vercel.app/"

    # Text to go before copyright information
    prefix = "[a project in HUGO-386](https://github.com/Samael3003/hugo-386)"

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = "This site"

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "All posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "api"
    tabWidth = 4
